### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by myleshyson** [markhuot/craft-pest#108]
Hey just wondering when this will support Craft 5.x? We're looking to update soon and I'm wondering if I should fork this for the time being or if there's a 5.x branch coming soon.

**Comment by leevigraham** [comment]
Not sure how but I managed to require `craft-pest` with composer in a Craft 5 site even though the `craft-pest` requirements are `"craftcms/cms": "^3.7|^4.0",`.

Running `./craft pest` throws a few errors so it's obviously not currently working with Craft 5.

![image](https://github.com/user-attachments/assets/05da50db-98c9-44f8-ae10-572bc9931b6f)

**Comment by markhuot** [comment]
Welp, it's working-ish now. Version 2 should support Craft 4.5+, 5+ and Pest 2 or Pest 3!
