### ISSUE TITLE
Support for forms

### ISSUE THREAD

**Issue by ostark** [markhuot/craft-pest#21]
Post requests should be supported as well. I'm wondering how we should implement it.

### Codeception style as a reference

```php
$I->amOnPage('/search-test');
$I->fillField('#searchText', 'Search query');
$I->click('#submit');
```

### Variant 1: Interacting with a real form

```php

// Get the page with the form
$form = $this->get("/page-with-form")
        ->assertOk()
        ->querySelector('form-selector')
       // or 
      ->form('form-selector');

// Fill and submit the form
$form
  ->fill('#searchText', 'Search query')
  ->submit()
  ->assertRedirectTo("/page-with-form", 301)
  ->assertSuccess("Expected success message");
```

### Variant 2: Create a request object

```php

$data = request()
   ->input('name-of-input', 'Search query')
   ->input('something-else, 1);

$this->post("/page-with-form", $data)
  ->assertRedirectTo("/page-with-form", 301)
  ->assertError("Expected error message");
```

Implementing both ways is possible, but I'm not sure if it is useful.

**Comment by ostark** [comment]
Let's try variant 1, as discussed in the backroom :-)

**Comment by ostark** [comment]
The [Entry Form](https://craftcms.com/docs/3.x/dev/controller-actions.html#post-entries-save-entry) is something I never worked with but it should be covered as well ... Not sure if it makes a differernce.

**Comment by markhuot** [comment]
Yup, I love this idea. I think it’s worth extra complexity to get to a point where the form interaction remains as terse as possible. My ideal API would be,

```php
get(‘/some/form/page’)
  ->assertOk()
  ->fill(‘title’, ‘Foo Bar’)
  ->fill(‘entryType’, ‘posts’)
  ->click(‘Save’)
  ->assertOk()
  ->assertFlash(‘Entry saved’);
```

Internally I think we can accomplish this by:

1. whenever `fill` is called we track that as stored state data.
2. when `click` is called we can use `querySelector` to grab all the `input` elements (and other form fields) then merge that form data with our `fill`-ed data.
3. `click` would kick off another request and return the response so it could be chained on to the fluent chain.

One note: `fill` and `click` should probably take a CSS selector to make things consistent. But a shorthand of looking for things with a `name=` attribute it a button text content would make for shorter calls.

**Comment by ostark** [comment]
I'm almost there (not handling the request/response so far)

**Comment by markhuot** [comment]
Note for myself, for later: 

https://twitter.com/diegohaz/status/1578567655493193728

some nice patterns in here.

**Comment by markhuot** [comment]
Closing now that there is initial support for forms. We can open more targeted tickets for specific features.
