### ISSUE TITLE
Make project config apply --force optional.

### ISSUE THREAD

**Issue by myleshyson** [markhuot/craft-pest#23]
Starting using this today (and LOVE IT), but one thing I noticed is that project-config/apply is set to run with the --force flag by default.

This is a problem because for sites like ours, witha massive project config, any tiny change in the config picked up by 'ProjectConfig::diff()' takes like 10+ minutes to apply, vs a few seconds for applying only the changes.

What do you think about removing the --force flag by default so only changes are applied, and then adding a command line option for people to add that flag if necessary?

I was thinking something like below if people really want to force config changes.

```sh
./craft pest/test --force // OR
./craft pest/test -f 
```

If you're open to it I'm happy to open a pull request!

**Comment by markhuot** [comment]
Nah, that was a bit over-eager. I think we can just remove the `--force` bits. If someone _really_ wants to be strict about it they can manually run `project-config/apply --force` in a bash script or in their CI run.
