### ISSUE TITLE
More flexible assertLocation()

### ISSUE THREAD

**Issue by ostark** [markhuot/craft-pest#66]
Honestly, I don't know a good solution, but when testing the last step of the Commerce checkout process I'm in the need to skip query parameters because it's dynamic.

Ideas:

```
assertLocation(string $location, array $parts = null)
```

```
assertLocation(string $location, bool $skipQuery = false)
```

```
assertLocation(string $location, bool $pathOnly = false) 
```

do you have a better idea?

**Comment by markhuot** [comment]
I added a `parts` param to `->assertLocation` allowing you to specify which parts (via PHP’s `parse_url`) are checked. E.g.,

```php
$response->assertLocation(‘/foo’, [‘path’]);
```

There’s also a sugar method for this common use case,

```php
$response->assertLocationPath(‘/foo’);
```

https://github.com/markhuot/craft-pest/blob/b82df3a4a01e98e153f32f8dd2dcd02a76c13d39/docs/assertions/response.md
