### ISSUE TITLE
Getting a Composer "minimum-stability" error on install

### ISSUE THREAD

**Issue by aaronbushnell** [markhuot/craft-pest#69]
When I try to install Pest for Craft CMS I get the following error—

```
In PackageDiscoveryTrait.php line 327:
                                                                                                                              
  Could not find a version of package markhuot/craft-pest matching your minimum-stability (stable). Require it with an expli  
  cit version constraint allowing its desired stability.                                                                      
```

This happens in both Craft 3.x and 4.x FWIW!

**Comment by aaronbushnell** [comment]
I presume it's because (at least for now) you need to run the install using something like this?
```
composer require markhuot/craft-pest:1.0.0-alpha10 --dev
```

**Comment by markhuot** [comment]
Yup, until it reaches a stable version you have to declare the version constraint explicitly, like you have. Once it’s stable (which it basically is) this requirement will fade away.

**Comment by aaronbushnell** [comment]
Awesome, thanks a bunch, @markhuot!
